# Generated by Django 5.2.5 on 2025-08-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='company',
        ),
        migrations.AddField(
            model_name='callplan',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_calls', to='calling_app.phone'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='used_warehouses', to='calling_app.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_warehouses', to='calling_app.company'),
        ),
        migrations.RemoveField(
            model_name='call',
            name='company',
        ),
        migrations.AddField(
            model_name='call',
            name='company',
            field=models.ManyToManyField(related_name='calls', to='calling_app.company'),
        ),
    ]
