# Generated by Django 5.2.5 on 2025-09-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_app', '0002_remove_warehouse_company_callplan_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='Склад', max_length=255, unique=True),
        ),
    ]
