# Generated by Django 5.2.5 on 2025-09-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_app', '0004_companystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='calling_app.companystatus'),
        ),
    ]
