# Generated by Django 5.2.5 on 2025-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calling_app', '0005_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='callplan',
            name='status',
            field=models.CharField(choices=[('on', 'Active'), ('off', 'Inactive')], default='on', max_length=3),
        ),
    ]
